# Generated by Django 2.2.12 on 2020-05-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='displayName_sn',
            new_name='sn_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='displayName_tm',
            new_name='tm_name',
        ),
        migrations.AddField(
            model_name='division',
            name='sn_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='tm_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='organization/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='division_type',
            field=models.CharField(max_length=50),
        ),
    ]
