# Generated by Django 2.2.12 on 2020-05-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INCIDENT_ASSIGNED', 'Incident assigned'), ('INCIDENT_CLOSED', 'Incident closed'), ('OTHER', 'Custom notification type')], max_length=50),
        ),
    ]
