# Generated by Django 2.2.12 on 2020-05-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36, unique=True)),
                ('top_category', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
                ('sn_top_category', models.CharField(max_length=200)),
                ('sn_sub_category', models.CharField(max_length=200)),
                ('tm_top_category', models.CharField(max_length=200)),
                ('tm_sub_category', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sn_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('sn_name', models.CharField(max_length=200)),
                ('sn_province', models.CharField(max_length=200)),
                ('tm_name', models.CharField(max_length=200)),
                ('tm_province', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PoliceDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sn_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36, unique=True)),
                ('party_type', models.CharField(blank=True, choices=[('REGISTERED_PARTY', 'Registered Party'), ('NON_REGISTERED_PARTY', 'Non Registered Party'), ('INDEPENDENT_GROUP', 'Independent Group')], max_length=50, null=True)),
                ('name', models.CharField(max_length=200)),
                ('sn_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PollingDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sn_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sn_name', models.CharField(max_length=100)),
                ('tm_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sn_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.District')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('sn_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sn_division', models.CharField(blank=True, max_length=200, null=True)),
                ('tm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tm_division', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.District')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sn_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, db_column='district_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.District', to_field='code')),
                ('division', models.ForeignKey(blank=True, db_column='division_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.PoliceDivision', to_field='code')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='GNDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sn_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.District')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DSDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sn_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.District')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
