# Generated by Django 2.2.12 on 2020-05-17 15:23

from django.db import migrations, models
import django.db.models.deletion
import functools
import src.file_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=functools.partial(src.file_upload.models._update_filename, *(), **{'path': ''}))),
                ('original_name', models.TextField()),
                ('extension', models.CharField(default='no_ext', max_length=20)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.Incident')),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
