# Generated by Django 2.2.12 on 2020-04-25 11:33

from django.db import migrations, models
import django.db.models.deletion
import src.incidents.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0042_auto_20200415_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('sn_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('gn_division', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_type', models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization')], default=src.incidents.models.ContactType('Individual'), max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.Recipient'),
        ),
    ]
