# Generated by Django 2.2.12 on 2020-04-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0043_auto_20200425_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='contact_type',
            new_name='recipient_type',
        ),
        migrations.AddField(
            model_name='recipient',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
