# Generated by Django 2.2.12 on 2020-05-02 19:10

from django.db import migrations, models
import src.incidents.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0047_cannedresponse_sendcannedresponseworkflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='di_division',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='election',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='letter_date',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='police_division',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='police_station',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='polictical_party',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='polling_division',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='polling_station',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='reporter',
            name='accused_name',
        ),
        migrations.RemoveField(
            model_name='reporter',
            name='accused_political_affiliation',
        ),
        migrations.RemoveField(
            model_name='reporter',
            name='political_affiliation',
        ),
        migrations.RemoveField(
            model_name='reporter',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='incident',
            name='language',
            field=models.CharField(choices=[('SINHALA', 'Sinhala'), ('TAMIL', 'Tamil'), ('ENGLISH', 'English')], default=src.incidents.models.LanguageType('English'), max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='nic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms'), ('MISS', 'Miss'), ('DR', 'Dr'), ('PROFESSOR', 'Professor')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='gn_division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='nic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms'), ('MISS', 'Miss'), ('DR', 'Dr'), ('PROFESSOR', 'Professor')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='reporter_type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization')], default=src.incidents.models.ContactType('Individual'), max_length=50, null=True),
        ),
    ]
