# Generated by Django 2.2.12 on 2020-05-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0050_auto_20200507_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ('created_date',), 'permissions': (('CAN_REVIEW_INCIDENTS', 'Can review created incidents'), ('CAN_REVIEW_OWN_INCIDENTS', 'Can review own incidents'), ('CAN_REVIEW_ALL_INCIDENTS', 'Can review all incidents'), ('CAN_MANAGE_INCIDENT', 'Can manage incident'), ('CAN_RUN_WORKFLOW', 'Can run incident workflows'), ('CAN_CHANGE_ASSIGNEE', 'Can change incident assignee'), ('CAN_VERIFY_INCIDENT', 'Can verify incident'), ('CAN_CLOSE_INCIDENT', 'Can close incident'), ('CAN_ESCALATE_INCIDENT', 'Can escalate incident'), ('CAN_ESCALATE_EXTERNAL', 'Can refer incident to external organization'), ('CAN_INVALIDATE_INCIDENT', 'Can invalidate incident'), ('CAN_REOPEN_INCIDENT', 'Can reopen incident'), ('CAN_ACTION_OVER_CURRENT_ASSIGNEE', 'Can action over current assignee'), ('CAN_VIEW_REPORTS', 'Can view inciddent reports'))},
        ),
    ]
